
  CREATE TABLE "TEAM12"."TASKS" 
   (	"ID" NUMBER(20,0) NOT NULL ENABLE, 
	"OWNER_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"WORKER_ID" NUMBER(20,0), 
	"NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"DEADLINE" DATE, 
	"PAYMENT" NUMBER(10,2), 
	"PICKUP_LOC" "SDO_GEOMETRY", 
	"DROPOFF_LOC" "SDO_GEOMETRY", 
	"PICKUP_ADDR" VARCHAR2(1000 BYTE), 
	"DROPOFF_ADDR" VARCHAR2(1000 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"WORKER_LOC" "MDSYS"."SDO_GEOMETRY" , 
	 CONSTRAINT "TASKS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
INSERT	INTO	USER_SDO_GEOM_METADATA	(TABLE_NAME,	
COLUMN_NAME,	DIMINFO,	SRID)	VALUES	('TASKS','PICKUP_LOC',
MDSYS.SDO_DIM_ARRAY(
MDSYS.SDO_DIM_ELEMENT('LAT',	-90.0,	90.0,	0.005),
MDSYS.SDO_DIM_ELEMENT('LONG',	-180.0,	180.0,	0.005)),8307);	

INSERT	INTO	USER_SDO_GEOM_METADATA	(TABLE_NAME,	
COLUMN_NAME,	DIMINFO,	SRID)	VALUES	('TASKS','DROPOFF_LOC',
MDSYS.SDO_DIM_ARRAY(
MDSYS.SDO_DIM_ELEMENT('LAT',	-90.0,	90.0,	0.005),
MDSYS.SDO_DIM_ELEMENT('LONG',	-180.0,	180.0,	0.005)),8307);	

INSERT	INTO	USER_SDO_GEOM_METADATA	(TABLE_NAME,	
COLUMN_NAME,	DIMINFO,	SRID)	VALUES	('TASKS','WORKER_LOC',
MDSYS.SDO_DIM_ARRAY(
MDSYS.SDO_DIM_ELEMENT('LAT',	-90.0,	90.0,	0.005),
MDSYS.SDO_DIM_ELEMENT('LONG',	-180.0,	180.0,	0.005)),8307);	

  CREATE INDEX "TEAM12"."DROPOFF_LOC_IDX" ON "TEAM12"."TASKS" ("DROPOFF_LOC") 
   INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
 

  CREATE INDEX "TEAM12"."PICKUP_LOC_IDX" ON "TEAM12"."TASKS" ("PICKUP_LOC") 
   INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
 

  CREATE INDEX "TEAM12"."WORKER_LOC_IDX" ON "TEAM12"."TASKS" ("WORKER_LOC") 
   INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
 

  CREATE OR REPLACE TRIGGER "TEAM12"."TASKS_SEQ_TRIGGER" 
before insert on TASKS
for each row
begin
select TASKS_SEQ.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "TEAM12"."TASKS_SEQ_TRIGGER" ENABLE;
 

  CREATE TABLE "TEAM12"."USERS" 
   (	"ID" NUMBER(20,0) NOT NULL ENABLE, 
	"LOGIN" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"PASS" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"IMEI" NUMBER(15,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"PROFILE_PIC" VARCHAR2(100 BYTE), 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE INDEX "TEAM12"."EMAIL" ON "TEAM12"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE UNIQUE INDEX "TEAM12"."LOGIN_IDX" ON "TEAM12"."USERS" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE INDEX "TEAM12"."PASS_IDX" ON "TEAM12"."USERS" ("PASS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "TEAM12"."USERS_SEQ_TRIGGER" 
before insert on USERS
for each row
begin
select users_seq.nextval into :new.ID from dual;
end;
/
ALTER TRIGGER "TEAM12"."USERS_SEQ_TRIGGER" ENABLE;
 
 
  CREATE TABLE "TEAM12"."RATINGS" 
   (	"FROM_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"TO_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"RATING" NUMBER(2,0) NOT NULL ENABLE, 
	"TASK_ID" NUMBER(20,0) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
 